import { SpanStatusCode } from "@opentelemetry/api";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { tracer } from "../src/app/otel/tracer";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleClick = () => {
    void tracer.startActiveSpan("requestToApi", async (span) => {
      try {
        await axios.get("/api?_vercel_no_cache=1");
      } catch (thrown) {
        span.setStatus({
          code: SpanStatusCode.ERROR,
        });
      } finally {
        console.log({ span });
        span.end();
      }
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <button type="button" onClick={handleClick} className={styles.card}>
            <h2>Send trace &rarr;</h2>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
